### PR TITLE
Update actions.py

### PR DESCRIPTION
**Pull request by johannesWen**
Added an optional tolerance offset of the entity/target's synchronization position. 
This tolerance is now supported in esmini ([767be1c](https://github.com/esmini/esmini/commit/767be1c10f70fcdad55738e00b09b362a4d7c2ce)).

### CODE REVIEW

**Comment by eknabevcc** [comment]
Before adding here, can you help me choose XSD/syntax?
The way I first proposed (adding attributes to the position elements) I don't think is possible - at least I can't see how the XSD would look like and still be backward compatible - which is a string requirement.
So, I found an alternative solution, which as been proposed to OSC 1.1, which is to add the two attributes to the main SynchronizeAction element instead.
See https://github.com/esmini/esmini/issues/48.
I lean towards the latter (adding action attributes). What do you say?
Maybe you see a solution of making first syntax backward compatible, in terms of xsd?

**Comment by MandolinMicke** [comment]
I suggest to sync with proposed changes in [esmini/esmini#48](https://github.com/esmini/esmini/issues/48#issuecomment-723988550), that will be possible to add in the "OpenSCENARIO" xsd without having backwards compability issues (this is synced with eknabevcc)

This way, the attributes will be in the SyncronizeAction (hence move those if statements in get_element to get_attributes)
And please update the class documentation (line 1502-1527) with the new attributes and and parameters. 
And for now also add something like this "NOTE: Not officially part of OpenSCENARIO but supported in esmini"

And please add the same changes to the RelativeSynchronizeAction aswell as the AbsoluteSynchronizeAction, to be consistent.

**Comment by johannesWen** [comment]
Yes, I agree with you. I will update the code later on today.

**Comment by eknabevcc** [comment]
For your info: esmini has been updated according to the "action attribute" option 👍 - which is aligned with what has been proposed for OSC 1.1. 
But, please note that there is no guarantee that OSC 1.1 will adopt it. But it will be a nice extension  feature in esmini regardless :) (and not violating OSC)

**Comment by MandolinMicke** [comment]
The attributes in get_element are still there

**Comment by johannesWen** [comment]
I am not quite sure what you mean, because get_element() is unchanged and the if statements are in get_attributes() now.

**Comment by MandolinMicke** [comment]
Sry, my missread...

I'll lookinto it this afternoon, need to update the documentation aswell, 
if you want to speed it up you can do that aswell, otherwise I'll fix it.

**Pull request merged**
